In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

## First argument is row and second argument is column

In [4]:
df.iloc[4][4]

'male'

In [5]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [6]:
df.iloc[1:5]

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [7]:
df.head(20)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female   NaN      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S  
15      0            248706  16.0000   NaN        S  
16      1            382652  29.1250   NaN        Q  
17      0            244373  13.0000   NaN        S  
18      0            345763  18.0000   NaN        S  
19      0              2649   7.2250   NaN        C

In [8]:
df1 = pd.DataFrame()

In [9]:
df1['Name'] = ['Steve Smith', 'Virat Kholi']

In [10]:
df1['Age'] = [24,25]

In [11]:
df1

Name  Age
0  Steve Smith   24
1  Virat Kholi   25

In [12]:
df1['Country'] = ['Australia', 'India']

In [13]:
df1

Name  Age    Country
0  Steve Smith   24  Australia
1  Virat Kholi   25      India

In [14]:
df1.set_index('Name')

Age    Country
Name                       
Steve Smith   24  Australia
Virat Kholi   25      India

In [15]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [16]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [18]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [19]:
df[df['Pclass'] == 3].head()

PassengerId  Survived  Pclass                            Name     Sex  \
0            1         0       3         Braund, Mr. Owen Harris    male   
2            3         1       3          Heikkinen, Miss. Laina  female   
4            5         0       3        Allen, Mr. William Henry    male   
5            6         0       3                Moran, Mr. James    male   
7            8         0       3  Palsson, Master. Gosta Leonard    male   

    Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0  22.0      1      0         A/5 21171   7.2500   NaN        S  
2  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
4  35.0      0      0            373450   8.0500   NaN        S  
5   NaN      0      0            330877   8.4583   NaN        Q  
7   2.0      3      1            349909  21.0750   NaN        S

In [20]:
df[df['Name'] == "Braund, Mr. Owen Harris"]

PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  
0      0  A/5 21171  7.25   NaN        S

In [21]:
df1

Name  Age    Country
0  Steve Smith   24  Australia
1  Virat Kholi   25      India

In [22]:
df1[df1['Name'] == "Virat Kholi"]

Name  Age Country
1  Virat Kholi   25   India

In [23]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [24]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [25]:
df[df['Embarked'] != 'S'].head(10)

PassengerId  Survived  Pclass  \
1             2         1       1   
5             6         0       3   
9            10         1       2   
16           17         0       3   
19           20         1       3   
22           23         1       3   
26           27         0       3   
28           29         1       3   
30           31         0       1   
31           32         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
5                                    Moran, Mr. James    male   NaN      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
16                               Rice, Master. Eugene    male   2.0      4   
19                            Masselmani, Mrs. Fatima  female   NaN      0   
22                        McGowan, Miss. Anna "Annie"  female  15.0      0   
26                            Emir, Mr. Farred Chehab    male   NaN      0   
28                      O'Dwyer, Miss. Ellen "Nellie"  female   NaN      0   
30                           Uruchurtu, Don. Manuel E    male  40.0      0   
31     Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN      1   

    Parch    Ticket      Fare Cabin Embarked  
1       0  PC 17599   71.2833   C85        C  
5       0    330877    8.4583   NaN        Q  
9       0    237736   30.0708   NaN        C  
16      1    382652   29.1250   NaN        Q  
19      0      2649    7.2250   NaN        C  
22      0    330923    8.0292   NaN        Q  
26      0      2631    7.2250   NaN        C  
28      0    330959    7.8792   NaN        Q  
30      0  PC 17601   27.7208   NaN        C  
31      0  PC 17569  146.5208   B78        C

## Removing the duplicates from the dataset

In [26]:
df['Embarked'].isnull().sum()

2

In [27]:
df.drop_duplicates(subset=['Embarked'], keep='last')

PassengerId  Survived  Pclass                                       Name  \
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   
888          889         0       3   Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                      Behr, Mr. Karl Howell   
890          891         0       3                        Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
829  female  62.0      0      0      113572  80.00   B28      NaN  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [28]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [29]:
df.groupby(['Sex', 'Survived'])['Age'].mean()

Sex     Survived
female  0           25.046875
        1           28.847716
male    0           31.618056
        1           27.276022
Name: Age, dtype: float64

In [30]:
df.groupby('Sex').mean()

PassengerId  Survived    Pclass        Age     SibSp     Parch  \
Sex                                                                      
female   431.028662  0.742038  2.159236  27.915709  0.694268  0.649682   
male     454.147314  0.188908  2.389948  30.726645  0.429809  0.235702   

             Fare  
Sex                
female  44.479818  
male    25.523893

In [31]:
df.groupby(['Sex','Pclass', 'Survived'])['Age'].mean()

Sex     Pclass  Survived
female  1       0           25.666667
                1           34.939024
        2       0           36.000000
                1           28.080882
        3       0           23.818182
                1           19.329787
male    1       0           44.581967
                1           36.248000
        2       0           33.369048
                1           16.022000
        3       0           27.255814
                1           22.274211
Name: Age, dtype: float64

## Grouping the by timestamp

In [32]:
ts_index = pd.date_range('01/01/2017', periods=200000, freq='60S')

In [33]:
df = pd.DataFrame(index=ts_index)

In [34]:
df.columns

Index([], dtype='object')

In [35]:
df = pd.read_csv('train.csv')

In [36]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [37]:
df = df.drop_duplicates(subset=['Embarked'], keep='last')

In [38]:
df.head()

PassengerId  Survived  Pclass                                       Name  \
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   
888          889         0       3   Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                      Behr, Mr. Karl Howell   
890          891         0       3                        Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
829  female  62.0      0      0      113572  80.00   B28      NaN  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [39]:
ts_index = pd.date_range('01/01/2017', periods=200000, freq='60S')

In [40]:
df = pd.DataFrame(index=ts_index)

In [41]:
df.columns

Index([], dtype='object')

In [42]:
df['no_of_vehicles'] = np.random.randint(1,10,200000)

In [43]:
df.head()

no_of_vehicles
2017-01-01 00:00:00               2
2017-01-01 00:01:00               8
2017-01-01 00:02:00               7
2017-01-01 00:03:00               2
2017-01-01 00:04:00               7

In [44]:
df.tail()

no_of_vehicles
2017-05-19 21:15:00               3
2017-05-19 21:16:00               9
2017-05-19 21:17:00               8
2017-05-19 21:18:00               8
2017-05-19 21:19:00               2

In [45]:
df.resample('2W').sum()

no_of_vehicles
2017-01-01            7225
2017-01-15          100855
2017-01-29          100442
2017-02-12          100400
2017-02-26          100410
2017-03-12          100429
2017-03-26          100444
2017-04-09          100592
2017-04-23          101093
2017-05-07          100528
2017-05-21           85798

In [46]:
df.resample('M').sum()

no_of_vehicles
2017-01-31          222835
2017-02-28          201127
2017-03-31          222080
2017-04-30          216134
2017-05-31          136040

## TimeStamp Split into Year, Month, Day, Dayofweek

In [47]:
ts_value = pd.date_range('01/01/2017', periods=200000, freq='15S')

In [48]:
df2 = pd.DataFrame()

In [49]:
df2['Datetime'] = ts_value

In [50]:
df2.tail()

Datetime
199995 2017-02-04 17:18:45
199996 2017-02-04 17:19:00
199997 2017-02-04 17:19:15
199998 2017-02-04 17:19:30
199999 2017-02-04 17:19:45

In [51]:
df2['Year'] = df2.Datetime.dt.year

In [52]:
df['Month'] = df2.Datetime.dt.month

In [53]:
df2.head()

Datetime  Year
0 2017-01-01 00:00:00  2017
1 2017-01-01 00:00:15  2017
2 2017-01-01 00:00:30  2017
3 2017-01-01 00:00:45  2017
4 2017-01-01 00:01:00  2017

In [54]:
df2['Day'] = df2.Datetime.dt.day

In [55]:
df2['weekday_name'] = df2.Datetime.dt.weekday_name

In [56]:
df2.columns


Index(['Datetime', 'Year', 'Day', 'weekday_name'], dtype='object')

In [57]:
df2['Hour'] = df2.Datetime.dt.hour
df2['Minutes'] = df2.Datetime.dt.minute
df2['Seconds'] = df2.Datetime.dt.second
df2['Microseconds'] = df2.Datetime.dt.microsecond

In [58]:
df2.columns

Index(['Datetime', 'Year', 'Day', 'weekday_name', 'Hour', 'Minutes', 'Seconds',
       'Microseconds'],
      dtype='object')

In [59]:
df2.head(10)

Datetime  Year  Day weekday_name  Hour  Minutes  Seconds  \
0 2017-01-01 00:00:00  2017    1       Sunday     0        0        0   
1 2017-01-01 00:00:15  2017    1       Sunday     0        0       15   
2 2017-01-01 00:00:30  2017    1       Sunday     0        0       30   
3 2017-01-01 00:00:45  2017    1       Sunday     0        0       45   
4 2017-01-01 00:01:00  2017    1       Sunday     0        1        0   
5 2017-01-01 00:01:15  2017    1       Sunday     0        1       15   
6 2017-01-01 00:01:30  2017    1       Sunday     0        1       30   
7 2017-01-01 00:01:45  2017    1       Sunday     0        1       45   
8 2017-01-01 00:02:00  2017    1       Sunday     0        2        0   
9 2017-01-01 00:02:15  2017    1       Sunday     0        2       15   

   Microseconds  
0             0  
1             0  
2             0  
3             0  
4             0  
5             0  
6             0  
7             0  
8             0  
9             0

In [60]:
df3 = pd.read_csv('/home/akhil/Downloads/data_preprocessing/PythonForMachineLearning/Part14/Datapreprocessing.csv')

In [61]:
df3.head()

Country   Age  Gender Occupation Employment Status Employement Type  \
0   Poland  34.0    Male   Salaried               Yes        Permanent   
1    Spain  42.0  Female   Business               Yes        Temporary   
2  Germany  29.0    Male   Business                No        Temporary   
3    Spain  38.0    Male   Business                No        Permanent   
4  Germany  32.0    Male   Salaried               NaN        Permanent   

    Salary Purchased  
0  72000.0        No  
1  48000.0       Yes  
2  54000.0        No  
3  61000.0        No  
4      NaN       Yes

In [62]:
df3.isnull().sum()

Country              0
Age                  3
Gender               0
Occupation           2
Employment Status    3
Employement Type     3
Salary               4
Purchased            0
dtype: int64

In [63]:
df3.columns

Index(['Country', 'Age', 'Gender', 'Occupation', 'Employment Status',
       'Employement Type', 'Salary', 'Purchased'],
      dtype='object')

In [64]:
features = df3[['Country', 'Age', 'Gender', 'Occupation', 'Employment Status',
       'Employement Type', 'Salary']]

In [65]:
labels = df3['Purchased']

In [66]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
Country              20 non-null object
Age                  17 non-null float64
Gender               20 non-null object
Occupation           18 non-null object
Employment Status    17 non-null object
Employement Type     17 non-null object
Salary               16 non-null float64
dtypes: float64(2), object(5)
memory usage: 1.2+ KB


In [67]:
features.isnull().sum()

Country              0
Age                  3
Gender               0
Occupation           2
Employment Status    3
Employement Type     3
Salary               4
dtype: int64

In [68]:
labels.isnull().sum()

0

In [69]:
from sklearn.preprocessing import Imputer

In [70]:
imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)

/home/akhil/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [71]:
df3.columns

Index(['Country', 'Age', 'Gender', 'Occupation', 'Employment Status',
       'Employement Type', 'Salary', 'Purchased'],
      dtype='object')

In [72]:
features = df3.iloc[:, -1].values
labels = df3.iloc[:, -1].values

In [73]:
df3.head(20)

Country   Age  Gender Occupation Employment Status Employement Type  \
0    Poland  34.0    Male   Salaried               Yes        Permanent   
1     Spain  42.0  Female   Business               Yes        Temporary   
2   Germany  29.0    Male   Business                No        Temporary   
3     Spain  38.0    Male   Business                No        Permanent   
4   Germany  32.0    Male   Salaried               NaN        Permanent   
5    Poland  31.0  Female   Business               Yes        Temporary   
6     India   NaN  Female   Salaried               NaN        Temporary   
7    Poland  22.0  Female   Salaried               Yes    Self Employed   
8     India  38.0    Male   Business                No              NaN   
9    Poland  49.0    Male        NaN               Yes    Self Employed   
10   Brazil  34.0    Male   Salaried                No        Permanent   
11    Spain  42.0  Female   Business                No        Temporary   
12  Germany  29.0  Female   Business                No        Temporary   
13    Spain  38.0    Male   Business                No        Permanent   
14  Germany   NaN    Male   Salaried               Yes        Permanent   
15   Brazil  32.0  Female   Business               Yes        Temporary   
16    Spain   NaN  Female   Salaried               Yes        Temporary   
17  England  22.0  Female   Salaried               Yes              NaN   
18  Germany  38.0    Male   Business               Yes              NaN   
19  England  45.0    Male        NaN               NaN    Self Employed   

     Salary Purchased  
0   72000.0        No  
1   48000.0       Yes  
2   54000.0        No  
3   61000.0        No  
4       NaN       Yes  
5   58000.0       Yes  
6   52000.0        No  
7   79000.0       Yes  
8       NaN        No  
9   67000.0       Yes  
10  70000.0        No  
11  48000.0       Yes  
12  54000.0        No  
13  61000.0        No  
14      NaN       Yes  
15  58000.0       Yes  
16  52000.0       Yes  
17  85000.0       Yes  
18      NaN        No  
19  67000.0       Yes

In [74]:
cols = ['Occupation','Employment Status','Employement Type']

In [75]:
df3[cols] = df3[cols].fillna(df3.mode().iloc[0])

In [76]:
df3.head(20)

Country   Age  Gender Occupation Employment Status Employement Type  \
0    Poland  34.0    Male   Salaried               Yes        Permanent   
1     Spain  42.0  Female   Business               Yes        Temporary   
2   Germany  29.0    Male   Business                No        Temporary   
3     Spain  38.0    Male   Business                No        Permanent   
4   Germany  32.0    Male   Salaried               Yes        Permanent   
5    Poland  31.0  Female   Business               Yes        Temporary   
6     India   NaN  Female   Salaried               Yes        Temporary   
7    Poland  22.0  Female   Salaried               Yes    Self Employed   
8     India  38.0    Male   Business                No        Temporary   
9    Poland  49.0    Male   Business               Yes    Self Employed   
10   Brazil  34.0    Male   Salaried                No        Permanent   
11    Spain  42.0  Female   Business                No        Temporary   
12  Germany  29.0  Female   Business                No        Temporary   
13    Spain  38.0    Male   Business                No        Permanent   
14  Germany   NaN    Male   Salaried               Yes        Permanent   
15   Brazil  32.0  Female   Business               Yes        Temporary   
16    Spain   NaN  Female   Salaried               Yes        Temporary   
17  England  22.0  Female   Salaried               Yes        Temporary   
18  Germany  38.0    Male   Business               Yes        Temporary   
19  England  45.0    Male   Business               Yes    Self Employed   

     Salary Purchased  
0   72000.0        No  
1   48000.0       Yes  
2   54000.0        No  
3   61000.0        No  
4       NaN       Yes  
5   58000.0       Yes  
6   52000.0        No  
7   79000.0       Yes  
8       NaN        No  
9   67000.0       Yes  
10  70000.0        No  
11  48000.0       Yes  
12  54000.0        No  
13  61000.0        No  
14      NaN       Yes  
15  58000.0       Yes  
16  52000.0       Yes  
17  85000.0       Yes  
18      NaN        No  
19  67000.0       Yes

In [77]:
df3['Salary'].fillna(df3['Salary'].mean())

0     72000.0
1     48000.0
2     54000.0
3     61000.0
4     61625.0
5     58000.0
6     52000.0
7     79000.0
8     61625.0
9     67000.0
10    70000.0
11    48000.0
12    54000.0
13    61000.0
14    61625.0
15    58000.0
16    52000.0
17    85000.0
18    61625.0
19    67000.0
Name: Salary, dtype: float64

In [78]:
df3.head(20)

Country   Age  Gender Occupation Employment Status Employement Type  \
0    Poland  34.0    Male   Salaried               Yes        Permanent   
1     Spain  42.0  Female   Business               Yes        Temporary   
2   Germany  29.0    Male   Business                No        Temporary   
3     Spain  38.0    Male   Business                No        Permanent   
4   Germany  32.0    Male   Salaried               Yes        Permanent   
5    Poland  31.0  Female   Business               Yes        Temporary   
6     India   NaN  Female   Salaried               Yes        Temporary   
7    Poland  22.0  Female   Salaried               Yes    Self Employed   
8     India  38.0    Male   Business                No        Temporary   
9    Poland  49.0    Male   Business               Yes    Self Employed   
10   Brazil  34.0    Male   Salaried                No        Permanent   
11    Spain  42.0  Female   Business                No        Temporary   
12  Germany  29.0  Female   Business                No        Temporary   
13    Spain  38.0    Male   Business                No        Permanent   
14  Germany   NaN    Male   Salaried               Yes        Permanent   
15   Brazil  32.0  Female   Business               Yes        Temporary   
16    Spain   NaN  Female   Salaried               Yes        Temporary   
17  England  22.0  Female   Salaried               Yes        Temporary   
18  Germany  38.0    Male   Business               Yes        Temporary   
19  England  45.0    Male   Business               Yes    Self Employed   

     Salary Purchased  
0   72000.0        No  
1   48000.0       Yes  
2   54000.0        No  
3   61000.0        No  
4       NaN       Yes  
5   58000.0       Yes  
6   52000.0        No  
7   79000.0       Yes  
8       NaN        No  
9   67000.0       Yes  
10  70000.0        No  
11  48000.0       Yes  
12  54000.0        No  
13  61000.0        No  
14      NaN       Yes  
15  58000.0       Yes  
16  52000.0       Yes  
17  85000.0       Yes  
18      NaN        No  
19  67000.0       Yes

## Filling the missing values


In [79]:
cols

['Occupation', 'Employment Status', 'Employement Type']

In [80]:
cols = ['Age', 'Salary']

## Using mode() is more efficient and accurate for fill up the missing values

df3[cols] = df3[cols].fillna(df3.mode().iloc[0])

In [81]:
df3.head(30)

Country   Age  Gender Occupation Employment Status Employement Type  \
0    Poland  34.0    Male   Salaried               Yes        Permanent   
1     Spain  42.0  Female   Business               Yes        Temporary   
2   Germany  29.0    Male   Business                No        Temporary   
3     Spain  38.0    Male   Business                No        Permanent   
4   Germany  32.0    Male   Salaried               Yes        Permanent   
5    Poland  31.0  Female   Business               Yes        Temporary   
6     India   NaN  Female   Salaried               Yes        Temporary   
7    Poland  22.0  Female   Salaried               Yes    Self Employed   
8     India  38.0    Male   Business                No        Temporary   
9    Poland  49.0    Male   Business               Yes    Self Employed   
10   Brazil  34.0    Male   Salaried                No        Permanent   
11    Spain  42.0  Female   Business                No        Temporary   
12  Germany  29.0  Female   Business                No        Temporary   
13    Spain  38.0    Male   Business                No        Permanent   
14  Germany   NaN    Male   Salaried               Yes        Permanent   
15   Brazil  32.0  Female   Business               Yes        Temporary   
16    Spain   NaN  Female   Salaried               Yes        Temporary   
17  England  22.0  Female   Salaried               Yes        Temporary   
18  Germany  38.0    Male   Business               Yes        Temporary   
19  England  45.0    Male   Business               Yes    Self Employed   

     Salary Purchased  
0   72000.0        No  
1   48000.0       Yes  
2   54000.0        No  
3   61000.0        No  
4       NaN       Yes  
5   58000.0       Yes  
6   52000.0        No  
7   79000.0       Yes  
8       NaN        No  
9   67000.0       Yes  
10  70000.0        No  
11  48000.0       Yes  
12  54000.0        No  
13  61000.0        No  
14      NaN       Yes  
15  58000.0       Yes  
16  52000.0       Yes  
17  85000.0       Yes  
18      NaN        No  
19  67000.0       Yes

## Label Encoding 

In [82]:
# it basically converts categorical data containing strings into integers as the machine learning algorithm understands 
#only numerical data

In [83]:
from sklearn.preprocessing import LabelEncoder



In [84]:
encode = LabelEncoder()

In [85]:
df4 = pd.DataFrame({
    'total_bill' : [16.99,10.34,21.01,23.68,24.59],
    'tip' : [1.01,1.66,3.50,3.31,3.61],
    'sex' : ['Female','Male','Male','Male','Female'],
    'smoker' : ['No','No','No','No','No'],
    'day' : ['Sun','Sun','Sun','Sun','Sun'],
    'time' : ['Dinner','Dinner','Dinner','Dinner','Dinner',],
    'size' : [2,3,3,2,4]
})

In [86]:
df4.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [87]:
data = pd.get_dummies(df4['sex'])

In [88]:
data.head()

Female  Male
0       1     0
1       0     1
2       0     1
3       0     1
4       1     0

In [89]:
df4.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [90]:
new_df = df4

In [91]:
new_df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## Method 1

In [92]:
data = pd.get_dummies(new_df['sex'])

## Appending the old data set data() on new dataset

In [93]:
new_df.drop('sex', axis=1)

total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

In [94]:
new_df["Male"] = data["Male"].to_list()
new_df["Female"] = data["Male"].to_list()

In [95]:
new_df.head()

total_bill   tip     sex smoker  day    time  size  Male  Female
0       16.99  1.01  Female     No  Sun  Dinner     2     0       0
1       10.34  1.66    Male     No  Sun  Dinner     3     1       1
2       21.01  3.50    Male     No  Sun  Dinner     3     1       1
3       23.68  3.31    Male     No  Sun  Dinner     2     1       1
4       24.59  3.61  Female     No  Sun  Dinner     4     0       0

In [96]:
new_df.drop('sex', axis='columns')

total_bill   tip smoker  day    time  size  Male  Female
0       16.99  1.01     No  Sun  Dinner     2     0       0
1       10.34  1.66     No  Sun  Dinner     3     1       1
2       21.01  3.50     No  Sun  Dinner     3     1       1
3       23.68  3.31     No  Sun  Dinner     2     1       1
4       24.59  3.61     No  Sun  Dinner     4     0       0

## Using label encoder

In [97]:
from sklearn.preprocessing import LabelEncoder

In [98]:
le = LabelEncoder()

In [99]:
labels = le.fit_transform(df4["sex"])

In [100]:
labels

array([0, 1, 1, 1, 0])

In [101]:
le.classes_

array(['Female', 'Male'], dtype=object)

## Appending this into our new DataFrame

In [102]:
df4["sex"] = labels

In [103]:
df4.head()

total_bill   tip  sex smoker  day    time  size  Male  Female
0       16.99  1.01    0     No  Sun  Dinner     2     0       0
1       10.34  1.66    1     No  Sun  Dinner     3     1       1
2       21.01  3.50    1     No  Sun  Dinner     3     1       1
3       23.68  3.31    1     No  Sun  Dinner     2     1       1
4       24.59  3.61    0     No  Sun  Dinner     4     0       0

In [104]:
df4.drop(['Male', 'Female'], axis='columns')

total_bill   tip  sex smoker  day    time  size
0       16.99  1.01    0     No  Sun  Dinner     2
1       10.34  1.66    1     No  Sun  Dinner     3
2       21.01  3.50    1     No  Sun  Dinner     3
3       23.68  3.31    1     No  Sun  Dinner     2
4       24.59  3.61    0     No  Sun  Dinner     4

In [105]:
labels2 = le.fit_transform(df4["smoker"])

In [106]:
labels2

array([0, 0, 0, 0, 0])

In [107]:
df4['smoker'] = labels2

In [108]:
df4

total_bill   tip  sex  smoker  day    time  size  Male  Female
0       16.99  1.01    0       0  Sun  Dinner     2     0       0
1       10.34  1.66    1       0  Sun  Dinner     3     1       1
2       21.01  3.50    1       0  Sun  Dinner     3     1       1
3       23.68  3.31    1       0  Sun  Dinner     2     1       1
4       24.59  3.61    0       0  Sun  Dinner     4     0       0

In [109]:
labels3 = le.fit_transform(df4["day"])

In [110]:
df4['day'] = labels3

In [111]:
df4

total_bill   tip  sex  smoker  day    time  size  Male  Female
0       16.99  1.01    0       0    0  Dinner     2     0       0
1       10.34  1.66    1       0    0  Dinner     3     1       1
2       21.01  3.50    1       0    0  Dinner     3     1       1
3       23.68  3.31    1       0    0  Dinner     2     1       1
4       24.59  3.61    0       0    0  Dinner     4     0       0

In [112]:
labels4 = le.fit_transform(df4['time'])

In [113]:
df4['time'] = labels4

In [114]:
df4

total_bill   tip  sex  smoker  day  time  size  Male  Female
0       16.99  1.01    0       0    0     0     2     0       0
1       10.34  1.66    1       0    0     0     3     1       1
2       21.01  3.50    1       0    0     0     3     1       1
3       23.68  3.31    1       0    0     0     2     1       1
4       24.59  3.61    0       0    0     0     4     0       0

## One Hot Encoding

In [115]:
#It is basically used to convert categorical data into boolean value

In [116]:
from sklearn.preprocessing import OneHotEncoder

In [117]:
one_hot_encode = OneHotEncoder(categorical_features=[0])
ohe = one_hot_encode.fit_transform(df4).toarray()

/home/akhil/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:414: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/akhil/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:450: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [118]:
ohe

array([[0.  , 1.  , 0.  , 0.  , 0.  , 1.01, 0.  , 0.  , 0.  , 0.  , 2.  ,
        0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 1.66, 1.  , 0.  , 0.  , 0.  , 3.  ,
        1.  , 1.  ],
       [0.  , 0.  , 1.  , 0.  , 0.  , 3.5 , 1.  , 0.  , 0.  , 0.  , 3.  ,
        1.  , 1.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  , 3.31, 1.  , 0.  , 0.  , 0.  , 2.  ,
        1.  , 1.  ],
       [0.  , 0.  , 0.  , 0.  , 1.  , 3.61, 0.  , 0.  , 0.  , 0.  , 4.  ,
        0.  , 0.  ]])

## Feature Scaling

In [119]:
#It is used to scale the data in a particular range for ex:-1 to 1
#why do we need this?Because if the data is not scaled not normalized we'll not be able to get the desired result or
#or the output can be miss leading 

In [120]:
from sklearn import preprocessing

In [121]:
x = np.array([[-400],[-100],[0],[100],[400]])

In [122]:
x

array([[-400],
       [-100],
       [   0],
       [ 100],
       [ 400]])

In [123]:
minmaxscaler = preprocessing.MinMaxScaler(feature_range=(0,1))

In [124]:
x_scaler = minmaxscaler.fit_transform(x)

In [125]:
x_scaler

array([[0.   ],
       [0.375],
       [0.5  ],
       [0.625],
       [1.   ]])

In [126]:
# Formula behind this
# (Xi -Xmin) / (Xmax - Xmin)
# (-100-(-400)) / (400-(-400))
# (-100 + 400) / (400 + 400)
# 300/800 = 3/8 = 0.375

## Applying to the pandas dataset

In [127]:
dataset = pd.read_csv('/home/akhil/Downloads/data_preprocessing/PythonForMachineLearning/Part22/Age-Salary.csv')

In [128]:
dataset.head()

ID  Gender  Age  Salary Purchased
0  1001    Male   21   21000        No
1  1002    Male   37   22000        No
2  1003  Female   28   45000        No
3  1004  Female   29   59000        No
4  1005    Male   21   78000        No

In [129]:
#Before colon it will be for ROWS & after colon it will be for COLUMNS

In [130]:
##Feature Extraction

In [131]:
features = dataset.iloc[:,[2,3]].values

In [132]:
features.shape


(200, 2)

In [133]:
minmaxscaler_as = preprocessing.MinMaxScaler(feature_range=(0,1))

In [134]:
feature_scale = minmaxscaler_as.fit_transform(features)

In [135]:
feature_scale

array([[0.02439024, 0.02962963],
       [0.41463415, 0.03703704],
       [0.19512195, 0.20740741],
       [0.2195122 , 0.31111111],
       [0.02439024, 0.45185185],
       [0.2195122 , 0.31851852],
       [0.2195122 , 0.51111111],
       [0.34146341, 1.        ],
       [0.17073171, 0.13333333],
       [0.41463415, 0.37037037],
       [0.19512195, 0.48148148],
       [0.19512195, 0.27407407],
       [0.04878049, 0.52592593],
       [0.34146341, 0.02222222],
       [0.        , 0.4962963 ],
       [0.26829268, 0.48148148],
       [0.70731707, 0.07407407],
       [0.65853659, 0.08148148],
       [0.68292683, 0.0962963 ],
       [0.73170732, 0.1037037 ],
       [0.65853659, 0.05185185],
       [0.70731707, 0.25185185],
       [0.73170732, 0.19259259],
       [0.65853659, 0.05185185],
       [0.68292683, 0.05925926],
       [0.70731707, 0.03703704],
       [0.75609756, 0.0962963 ],
       [0.70731707, 0.11111111],
       [0.26829268, 0.20740741],
       [0.31707317, 0.02222222],
       [0.

In [136]:
#StandardScaler

In [137]:
x

array([[-400],
       [-100],
       [   0],
       [ 100],
       [ 400]])

In [138]:
standard_scaler = preprocessing.StandardScaler()

In [139]:
x_scaler = standard_scaler.fit_transform(x)

In [140]:
x_scaler

array([[-1.53392998],
       [-0.38348249],
       [ 0.        ],
       [ 0.38348249],
       [ 1.53392998]])

In [141]:
x.mean()

0.0

In [142]:

x1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])


In [143]:
standard_scaler = minmaxscaler.fit_transform(x1)

In [144]:
standard_scaler

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

In [145]:
np.mean(x1[:,0])

4.0

In [146]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
ID           200 non-null int64
Gender       200 non-null object
Age          200 non-null int64
Salary       200 non-null int64
Purchased    200 non-null object
dtypes: int64(3), object(2)
memory usage: 7.9+ KB


In [147]:
features1 = dataset.iloc[:,[2,3]].values

In [148]:
scaled_features = minmaxscaler.fit_transform(features1)

In [149]:
scaled_features

array([[0.02439024, 0.02962963],
       [0.41463415, 0.03703704],
       [0.19512195, 0.20740741],
       [0.2195122 , 0.31111111],
       [0.02439024, 0.45185185],
       [0.2195122 , 0.31851852],
       [0.2195122 , 0.51111111],
       [0.34146341, 1.        ],
       [0.17073171, 0.13333333],
       [0.41463415, 0.37037037],
       [0.19512195, 0.48148148],
       [0.19512195, 0.27407407],
       [0.04878049, 0.52592593],
       [0.34146341, 0.02222222],
       [0.        , 0.4962963 ],
       [0.26829268, 0.48148148],
       [0.70731707, 0.07407407],
       [0.65853659, 0.08148148],
       [0.68292683, 0.0962963 ],
       [0.73170732, 0.1037037 ],
       [0.65853659, 0.05185185],
       [0.70731707, 0.25185185],
       [0.73170732, 0.19259259],
       [0.65853659, 0.05185185],
       [0.68292683, 0.05925926],
       [0.70731707, 0.03703704],
       [0.75609756, 0.0962963 ],
       [0.70731707, 0.11111111],
       [0.26829268, 0.20740741],
       [0.31707317, 0.02222222],
       [0.

In [150]:
dataset.head()

ID  Gender  Age  Salary Purchased
0  1001    Male   21   21000        No
1  1002    Male   37   22000        No
2  1003  Female   28   45000        No
3  1004  Female   29   59000        No
4  1005    Male   21   78000        No

In [151]:
#Normalizer

In [152]:
normalizer = preprocessing.Normalizer()

In [153]:
normalized_data = normalizer.fit_transform(x)

In [154]:
normalized_data

array([[-1.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 1.]])

## Detecting the outliers and Handeling them

In [155]:
dataset1 = pd.read_csv('/home/akhil/Downloads/data_preprocessing/PythonForMachineLearning/Part27/Salary.csv')

In [156]:
dataset1.head()

ID  Age  Salary
0  1001   33   81200
1  1002   25   63537
2  1003   24   51963
3  1004   23   40199
4  1005   34   39347

In [157]:
dataset1.shape


(599, 3)

In [158]:
dataset['Salary'].max()

152000

In [159]:
dataset1['Salary'].max()

81200

In [160]:
dataset1['Salary'].min()

350

In [161]:
dataset1['Salary'].mean()

5644.819699499165

In [162]:
dataset1[dataset1['Salary'] > 10000].count()

ID        57
Age       57
Salary    57
dtype: int64

## get dummies

In [163]:
data = {'firstname': ['Arun', 'Jebu', 'Venkat', 'Rekha', 'Majid','Mohsin'],
        'lastname': ['Kumar', 'Jacob', 'Raghavan', 'Singh', 'Khan','Khan'],
        'employmenttype': ['Service', 'Business', 'Student', 'Service', 'Business','Business'],
        'country' :['India','USA','USA','Sweden','Australia','Germany']}

In [164]:
data = pd.DataFrame(data)

In [165]:
data.head()

firstname  lastname employmenttype    country
0      Arun     Kumar        Service      India
1      Jebu     Jacob       Business        USA
2    Venkat  Raghavan        Student        USA
3     Rekha     Singh        Service     Sweden
4     Majid      Khan       Business  Australia

In [166]:
df1 = pd.get_dummies(data['employmenttype'])

In [167]:
df2 = pd.get_dummies(data['country'])

In [168]:
columns = ['firstname','lastname','employmenttype','country']

In [169]:
df = pd.DataFrame(data,columns)

In [170]:
result = pd.concat([df,df1,df1], axis=1)

In [171]:
result

firstname lastname employmenttype country  Business  Service  \
0                    NaN      NaN            NaN     NaN       0.0      1.0   
1                    NaN      NaN            NaN     NaN       1.0      0.0   
2                    NaN      NaN            NaN     NaN       0.0      0.0   
3                    NaN      NaN            NaN     NaN       0.0      1.0   
4                    NaN      NaN            NaN     NaN       1.0      0.0   
5                    NaN      NaN            NaN     NaN       1.0      0.0   
country              NaN      NaN            NaN     NaN       NaN      NaN   
employmenttype       NaN      NaN            NaN     NaN       NaN      NaN   
firstname            NaN      NaN            NaN     NaN       NaN      NaN   
lastname             NaN      NaN            NaN     NaN       NaN      NaN   

                Student  Business  Service  Student  
0                   0.0       0.0      1.0      0.0  
1                   0.0       1.0      0.0      0.0  
2                   1.0       0.0      0.0      1.0  
3                   0.0       0.0      1.0      0.0  
4                   0.0       1.0      0.0      0.0  
5                   0.0       1.0      0.0      0.0  
country             NaN       NaN      NaN      NaN  
employmenttype      NaN       NaN      NaN      NaN  
firstname           NaN       NaN      NaN      NaN  
lastname            NaN       NaN      NaN      NaN

## Probability mas  function(pmf)

In [172]:
list1 = [1,1,6,3,2,3,4,2,3,5,5,6,5,5,5,5,5,2,2,3,3,5,2,2,5,6,2,2,2,3,6,6,2,4,3,2,3] 

In [173]:
df5 = pd.DataFrame(list1)

In [174]:
df5

0
0   1
1   1
2   6
3   3
4   2
5   3
6   4
7   2
8   3
9   5
10  5
11  6
12  5
13  5
14  5
15  5
16  5
17  2
18  2
19  3
20  3
21  5
22  2
23  2
24  5
25  6
26  2
27  2
28  2
29  3
30  6
31  6
32  2
33  4
34  3
35  2
36  3

In [175]:
df2 = df1.rename(columns={0:'item_counts'})

In [176]:
df2

Business  Service  Student
0         0        1        0
1         1        0        0
2         0        0        1
3         0        1        0
4         1        0        0
5         1        0        0

## Pandas Pivot Tables and GroupBy Functionality

In [177]:
train = pd.read_csv('/home/akhil/Downloads/data_preprocessing/PythonForMachineLearning/Part1/train.csv')

In [178]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [179]:
train.groupby('Sex')[['Survived']].mean()

Survived
Sex             
female  0.742038
male    0.188908

In [180]:
train.groupby(['Sex','Pclass'])['Survived'].mean()

Sex     Pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: Survived, dtype: float64

## Sorting in Python

In [181]:
df6 = pd.DataFrame()

In [182]:
df6['Name'] = train['Name']
df6['Pclass'] = train['Name']

In [183]:
df6.sort_values(by='Name', ascending=True,inplace=True)

In [184]:
df6.head()

Name  \
845                    Abbing, Mr. Anthony   
746            Abbott, Mr. Rossmore Edward   
279       Abbott, Mrs. Stanton (Rosa Hunt)   
308                    Abelson, Mr. Samuel   
874  Abelson, Mrs. Samuel (Hannah Wizosky)   

                                    Pclass  
845                    Abbing, Mr. Anthony  
746            Abbott, Mr. Rossmore Edward  
279       Abbott, Mrs. Stanton (Rosa Hunt)  
308                    Abelson, Mr. Samuel  
874  Abelson, Mrs. Samuel (Hannah Wizosky)

## Feature Engineering

In [185]:
# It is a process of deriving new fields from existing field or columns in a dataset 


In [186]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [187]:
train['Family'] = train['SibSp'] + train['Parch'] + 1

In [188]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
Family         891 non-null int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB


In [189]:
train['FamSize'] = train['Family']

In [190]:
train['FamSize'].loc[train['Family'] == 1] = 'Small'

/home/akhil/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [191]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
Family         891 non-null int64
FamSize        891 non-null object
dtypes: float64(2), int64(6), object(6)
memory usage: 97.5+ KB


In [192]:
train['FamSize'].loc[(train['Family'] > 1) & (train['Family'] <= 5)] = 'Medium'

In [193]:
train['FamSize'].loc[train['Family'] > 5] = 'Big'

In [194]:
import warnings

In [195]:
warnings.filterwarnings('ignore')

In [196]:
train['Family'].loc[train['Family'] > 1] = 'WithFamily'

In [197]:
train['Family'].loc[train['Family'] == 1] = 'Alone'

In [198]:
train['FamSize'].value_counts()

Small     537
Medium    307
Big        47
Name: FamSize, dtype: int64

In [199]:
#selecting multiple columns of a pandas dataset

In [200]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
Family         891 non-null object
FamSize        891 non-null object
dtypes: float64(2), int64(5), object(7)
memory usage: 97.5+ KB


In [201]:
#Extracting 0, 3:6, 9:12

In [202]:
feature1 = train.iloc[:,0].values

In [203]:
feature2 = train.iloc[:,3:6].values

In [204]:
feature3 = train.iloc[:,9:12].values

In [205]:
feature1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [206]:
feature2

array([['Braund, Mr. Owen Harris', 'male', 22.0],
       ['Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'female',
        38.0],
       ['Heikkinen, Miss. Laina', 'female', 26.0],
       ...,
       ['Johnston, Miss. Catherine Helen "Carrie"', 'female', nan],
       ['Behr, Mr. Karl Howell', 'male', 26.0],
       ['Dooley, Mr. Patrick', 'male', 32.0]], dtype=object)

## Mapping External Values to Pandas Column

In [207]:
df = pd.DataFrame()


In [208]:
df['ID'] = [1111,2222,3333,4444,5555]

In [209]:
df['Name'] = ['Venkat','Soumya','Jatin','Nitin','Dupesh'] 

In [210]:
df['City'] = ['Hyderabad','Kolkata','Chandigarh','Bangalore','Jaipur'] 

In [211]:
city_to_state = {'Hyderabad':'Andhra Pradesh', 'Chandigarh':'Punjab', 'Jaipur':'Rajasthan', 'Kolkata':'West Bengal', 'Bangalore':'Karnataka'} 

In [212]:
df['State'] = df['City'].map(city_to_state)

In [213]:
df

ID    Name        City           State
0  1111  Venkat   Hyderabad  Andhra Pradesh
1  2222  Soumya     Kolkata     West Bengal
2  3333   Jatin  Chandigarh          Punjab
3  4444   Nitin   Bangalore       Karnataka
4  5555  Dupesh      Jaipur       Rajasthan

## Reading Tables from HTML page         

In [214]:
html_data = pd.read_html('https://en.wikipedia.org/wiki/2017_Indian_Premier_League')

In [215]:
html_data

[                       0                                             1
 0                  Dates                         5 April – 21 May 2017
 1       Administrator(s)  Board of Control for Cricket in India (BCCI)
 2         Cricket format                                      Twenty20
 3   Tournament format(s)               Double round robin and playoffs
 4                Host(s)                                         India
 5              Champions                    Mumbai Indians (3rd title)
 6             Runners-up                        Rising Pune Supergiant
 7           Participants                                             8
 8         Matches played                                            60
 9             Attendance                  1,592,543 (26,542 per match)
 10  Player of the series    Ben Stokes (RPS) (316 runs and 12 wickets)
 11             Most runs                      David Warner (SRH) (641)
 12          Most wickets                  Bhuvneshwar Kumar (SR

In [216]:
html_data0 = pd.read_html('https://en.wikipedia.org/wiki/2017_Indian_Premier_League')[0]

In [217]:
html_data0

0                                             1
0                  Dates                         5 April – 21 May 2017
1       Administrator(s)  Board of Control for Cricket in India (BCCI)
2         Cricket format                                      Twenty20
3   Tournament format(s)               Double round robin and playoffs
4                Host(s)                                         India
5              Champions                    Mumbai Indians (3rd title)
6             Runners-up                        Rising Pune Supergiant
7           Participants                                             8
8         Matches played                                            60
9             Attendance                  1,592,543 (26,542 per match)
10  Player of the series    Ben Stokes (RPS) (316 runs and 12 wickets)
11             Most runs                      David Warner (SRH) (641)
12          Most wickets                  Bhuvneshwar Kumar (SRH) (26)
13      Official website                                www.iplt20.com
14          ← 20162018 →                                  ← 20162018 →

## Label Encoding with user defined Function


In [218]:
#basically used to convert strings into numeric values

In [219]:
encode = LabelEncoder()

In [220]:
feature6 = train.iloc[:].values

In [221]:
label_index = [4,10]

In [222]:
df6 = pd.DataFrame(feature6)

In [223]:
def func_label_encoder(list1,features):
    encode = LabelEncoder()
    features6[list1] = encode.fit_transform(feature6)

In [224]:
var_le = ['Sex', 'Embarked']

## Preprocessing based on conditions 

In [225]:
# conditions to be applied
# Sex is male
# Pclass is 1 
# Age > 40
# Embarked is S

In [226]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
Family         891 non-null object
FamSize        891 non-null object
dtypes: float64(2), int64(5), object(7)
memory usage: 97.5+ KB


SyntaxError: invalid syntax (<ipython-input-240-6c3eb50eaa3e>, line 1)

In [236]:
test.value_counts().sum()

891

In [242]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
Family         891 non-null object
FamSize        891 non-null object
dtypes: float64(2), int64(5), object(7)
memory usage: 97.5+ KB


In [251]:
test2 = train['Age'] > 40

In [252]:
test2.value_counts().sum()

891

In [256]:
test3 = train['Embarked'] == 'S'

In [259]:
test3.value_counts()

True     644
False    247
Name: Embarked, dtype: int64

In [263]:
# Approach 2

In [264]:
train[(train['Age'] > 40) & (train['Embarked'] == "S")].head()

PassengerId  Survived  Pclass                              Name     Sex  \
6             7         0       1           McCarthy, Mr. Timothy J    male   
11           12         1       1          Bonnell, Miss. Elizabeth  female   
15           16         1       2  Hewlett, Mrs. (Mary D Kingcome)   female   
33           34         0       2             Wheadon, Mr. Edward H    male   
35           36         0       1    Holverson, Mr. Alexander Oskar    male   

     Age  SibSp  Parch      Ticket     Fare Cabin Embarked      Family FamSize  
6   54.0      0      0       17463  51.8625   E46        S       Alone   Small  
11  58.0      0      0      113783  26.5500  C103        S       Alone   Small  
15  55.0      0      0      248706  16.0000   NaN        S       Alone   Small  
33  66.0      0      0  C.A. 24579  10.5000   NaN        S       Alone   Small  
35  42.0      1      0      113789  52.0000   NaN        S  WithFamily  Medium

## Fit, transform and fit_transform

In [265]:
fft = pd.read_csv('/home/akhil/Downloads/data_preprocessing/PythonForMachineLearning/Part15/Datapreprocessing.csv')

In [266]:
fft.head()

Country   Age  Gender Occupation Employment Status Employement Type  \
0   Poland  34.0    Male   Salaried               Yes        Permanent   
1    Spain  42.0  Female   Business               Yes        Temporary   
2  Germany  29.0    Male   Business                No        Temporary   
3    Spain  38.0    Male   Business                No        Permanent   
4  Germany  32.0    Male   Salaried               NaN        Permanent   

    Salary Purchased  
0  72000.0        No  
1  48000.0       Yes  
2  54000.0        No  
3  61000.0        No  
4      NaN       Yes

In [268]:
fft.isnull().sum()

Country              0
Age                  3
Gender               0
Occupation           2
Employment Status    3
Employement Type     3
Salary               4
Purchased            0
dtype: int64

In [269]:
# We'll create an imputer to remove null values from age,occupation,es,et,salary

In [270]:
from sklearn.preprocessing import Imputer

In [272]:
imputer = Imputer(missing_values="NaN", strategy='mean', axis=0)

In [273]:
imputer.fit(fft[['Age', 'Salary']])

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [274]:
fft['Age'].mean()

35.0

In [276]:
imputer.transform(fft[['Age', 'Salary']])

array([[3.4000e+01, 7.2000e+04],
       [4.2000e+01, 4.8000e+04],
       [2.9000e+01, 5.4000e+04],
       [3.8000e+01, 6.1000e+04],
       [3.2000e+01, 6.1625e+04],
       [3.1000e+01, 5.8000e+04],
       [3.5000e+01, 5.2000e+04],
       [2.2000e+01, 7.9000e+04],
       [3.8000e+01, 6.1625e+04],
       [4.9000e+01, 6.7000e+04],
       [3.4000e+01, 7.0000e+04],
       [4.2000e+01, 4.8000e+04],
       [2.9000e+01, 5.4000e+04],
       [3.8000e+01, 6.1000e+04],
       [3.5000e+01, 6.1625e+04],
       [3.2000e+01, 5.8000e+04],
       [3.5000e+01, 5.2000e+04],
       [2.2000e+01, 8.5000e+04],
       [3.8000e+01, 6.1625e+04],
       [4.5000e+01, 6.7000e+04]])

In [277]:
fft.isnull().sum()

Country              0
Age                  3
Gender               0
Occupation           2
Employment Status    3
Employement Type     3
Salary               4
Purchased            0
dtype: int64

In [278]:
x = imputer.transform(fft[['Age', 'Salary']])

In [283]:
# You can do this in one step also
imputer.fit_transform(fft[['Age', 'Salary']])

array([[3.4000e+01, 7.2000e+04],
       [4.2000e+01, 4.8000e+04],
       [2.9000e+01, 5.4000e+04],
       [3.8000e+01, 6.1000e+04],
       [3.2000e+01, 6.1625e+04],
       [3.1000e+01, 5.8000e+04],
       [3.5000e+01, 5.2000e+04],
       [2.2000e+01, 7.9000e+04],
       [3.8000e+01, 6.1625e+04],
       [4.9000e+01, 6.7000e+04],
       [3.4000e+01, 7.0000e+04],
       [4.2000e+01, 4.8000e+04],
       [2.9000e+01, 5.4000e+04],
       [3.8000e+01, 6.1000e+04],
       [3.5000e+01, 6.1625e+04],
       [3.2000e+01, 5.8000e+04],
       [3.5000e+01, 5.2000e+04],
       [2.2000e+01, 8.5000e+04],
       [3.8000e+01, 6.1625e+04],
       [4.5000e+01, 6.7000e+04]])

In [284]:
# Using label encoding

In [285]:
encode = LabelEncoder()

In [286]:
encode.fit_transform(fft['Country'])

array([4, 5, 2, 5, 2, 4, 3, 4, 3, 4, 0, 5, 2, 5, 2, 0, 5, 1, 2, 1])

## Dropping specific columns of pandas dataset

In [287]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked      Family FamSize  
0      0         A/5 21171   7.2500   NaN        S  WithFamily  Medium  
1      0          PC 17599  71.2833   C85        C  WithFamily  Medium  
2      0  STON/O2. 3101282   7.9250   NaN        S       Alone   Small  
3      0            113803  53.1000  C123        S  WithFamily  Medium  
4      0            373450   8.0500   NaN        S       Alone   Small

In [288]:
df8 = train.loc[:, (df.columns != 'Survived') & (df.columns != 'Fare')]

In [289]:
df8.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  
0                            Braund, Mr. Owen Harris  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  
2                             Heikkinen, Miss. Laina  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  
4                           Allen, Mr. William Henry

In [290]:
# Method 2

In [292]:
train.drop(train.columns[[1]], axis=1, inplace=True)

In [294]:
train.drop(['Age'], axis=1, inplace=True)

In [296]:
train.drop(['Fare','Sex'],axis=1,inplace=True)

## KFold from sklearn.cross_validation 